#-- SPDX-FileCopyrightText: 2022 RTE FRANCE
# -- --
# SPDX-License-Identifier: Apache-2.0

# Setup
title:            CoMPAS SCT
tagline:          'CoMPAS project documentation'

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/com-pas/compas-sct

github_username:  com-pas
git_repo:         compas-sct
git_branch:       feat/117_Documentation_SCD_Generation_Process

baseurl:          /compas-sct
contributingUrl:  /contributing

defaults:
  - 
    scope:
      path: "HOME.md"
    values:
      permalink: "/"